// Generated by CoffeeScript 1.3.3
(function() {

  (function($, window) {
    var OmniSelect, document;
    document = window.document;
    OmniSelect = (function() {

      function OmniSelect(options) {
        this._options = $.extend({
          collection: '.omni-filter-collection',
          inputUrlArg: '',
          inputElemArg: '',
          outputElem: '',
          clearElem: '',
          addFilterLabel: 'add filter',
          removeFilterLabel: 'remove filter',
          onStart: function(tour) {},
          onAdd: function(tour) {},
          onDelete: function(tour) {},
          onSelect: function(tour) {}
        }, options);
      }

      OmniSelect.prototype.init = function() {
        var addFilterLink,
          _this = this;
        this._collectionInputs = [];
        this._collectionSelect = $('<select>');
        this._collectionSelect.append('<option>', {
          selected: '',
          value: ''
        });
        this._createCollectionSelect();
        this._removeFilterLink = $('<a>', {
          text: this._options.removeFilterLabel,
          "class": 'remove-filter-link',
          href: '#'
        });
        addFilterLink = $('<a>', {
          text: this._options.addFilterLabel,
          "class": 'add-filter-link',
          href: '#'
        });
        addFilterLink.click(function(event) {
          return _this._addFilter();
        });
        $(this._options.collection).append(addFilterLink);
        this.decode();
        if (this._options.onAdd != null) {
          return this._options.onAdd(this);
        }
      };

      OmniSelect.prototype.encode = function() {
        var c, child, counter, opts, str, _i, _j, _len, _len1, _ref;
        str = '';
        opts = $(this._options.collection).children('div');
        counter = 0;
        for (_i = 0, _len = opts.length; _i < _len; _i++) {
          child = opts[_i];
          if ($(child).children('div:first').find('select').val() !== "") {
            str += $(child).children('div:first').find('select').val();
            _ref = $(child).children('div:not(:first-child)');
            for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
              c = _ref[_j];
              str += ',';
              if ($(c).is('select,input')) {
                str += $(c).val();
              } else {
                str += $(c).find('select,input').val();
              }
            }
            counter += 1;
            if (counter < opts.length) {
              str += ';';
            }
          }
        }
        if (this._options.outputElem !== "") {
          $(this._options.outputElem).val = str;
        }
        return str;
      };

      OmniSelect.prototype.decode = function() {
        var filter, j, numFilters, opt, opts, rest_values, str, values, _i, _len, _results;
        str = "";
        if (this._options.inputElemArg !== "") {
          str = $(this._options.outputElem).val;
        }
        if (this._options.inputUrlArg !== "") {
          str = this._getURIParameter(this._options.inputUrlArg);
        }
        if (arguments.length > 0) {
          str = arguments[0];
        }
        if (!str) {
          str = "";
        }
        opts = str.split(';');
        numFilters = opts.length;
        if (opts[0] === "") {
          numFilters = 0;
        }
        if (numFilters === 0) {
          this.reset();
          return;
        }
        this.clear();
        _results = [];
        for (_i = 0, _len = opts.length; _i < _len; _i++) {
          opt = opts[_i];
          values = opt.split(',');
          filter = this._addFilter(false);
          filter.find('select').val(values[0]);
          this._selectFromCollectionSelect(filter.find('select'), false);
          if (filter.children().eq(1).find('select').is('[multiple]')) {
            rest_values = values.slice(1, values.length);
            _results.push(filter.children().eq(1).find('select,input').val(rest_values));
          } else {
            _results.push((function() {
              var _j, _ref, _results1;
              _results1 = [];
              for (j = _j = 1, _ref = filter.children().length - 1; 1 <= _ref ? _j <= _ref : _j >= _ref; j = 1 <= _ref ? ++_j : --_j) {
                _results1.push(filter.children().eq(j).find('select,input').val(values[j]));
              }
              return _results1;
            })());
          }
        }
        return _results;
      };

      OmniSelect.prototype.reset = function() {
        this.clear();
        return this._addFilter();
      };

      OmniSelect.prototype.clear = function() {
        return $(this._options.collection).children('div').remove();
      };

      OmniSelect.prototype._createCollectionSelect = function() {
        var child, counter, ele, eleWrap, newSelect, _i, _j, _len, _len1, _ref, _ref1, _results;
        counter = 0;
        _ref = $(this._options.collection).children('div');
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          child = _ref[_i];
          this._collectionSelect.append($('<option>', {
            text: $(child).children('label:first-child').text(),
            value: counter
          }));
          newSelect = [];
          _ref1 = $(child).children(':not(:first-child)');
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            ele = _ref1[_j];
            eleWrap = $('<div>');
            eleWrap.append(ele);
            newSelect.push(eleWrap[0]);
          }
          this._collectionInputs.push(newSelect);
          _results.push(++counter);
        }
        return _results;
      };

      OmniSelect.prototype._selectFromCollectionSelect = function(target, runOnSelect) {
        if (runOnSelect == null) {
          runOnSelect = true;
        }
        target.parent().parent().children(':not(:first-child):not(a)').remove();
        target.parent().after($(this._collectionInputs[target.val()]).clone());
        if (runOnSelect) {
          if (this._options.onSelect != null) {
            return this._options.onSelect(this);
          }
        }
      };

      OmniSelect.prototype._addFilter = function(runOnSelect) {
        var clonedSelectDiv, clonedSelectDivWrap, selectDiv,
          _this = this;
        if (runOnSelect == null) {
          runOnSelect = true;
        }
        selectDiv = $('<div>');
        selectDiv.append(this._collectionSelect);
        clonedSelectDiv = selectDiv.clone();
        clonedSelectDiv.children('select:first-child').change(function(event) {
          return _this._selectFromCollectionSelect($(event.target));
        });
        clonedSelectDivWrap = $('<div>', {
          "class": 'form-inline'
        });
        clonedSelectDivWrap.append(clonedSelectDiv);
        $(this._options.collection).children(':last-child').before(clonedSelectDivWrap);
        this._updateRemoveFilterButton();
        if (runOnSelect) {
          if (this._options.onAdd != null) {
            this._options.onAdd(this);
          }
        }
        return clonedSelectDivWrap;
      };

      OmniSelect.prototype._updateRemoveFilterButton = function() {
        var child, link, _i, _j, _len, _len1, _ref, _ref1, _results,
          _this = this;
        _ref = $(this._options.collection).children('div');
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          child = _ref[_i];
          if ($(child).children(':last-child').is('a')) {
            $(child).children(':last-child').remove();
          }
        }
        if ($(this._options.collection).children('div').length > 1) {
          _ref1 = $(this._options.collection).children('div');
          _results = [];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            child = _ref1[_j];
            link = this._removeFilterLink.clone();
            link.click(function(event) {
              return _this._removeFilter(event);
            });
            _results.push($(child).append(link));
          }
          return _results;
        }
      };

      OmniSelect.prototype._removeFilter = function(event) {
        $(event.target).parent().remove();
        return this._updateRemoveFilterButton();
      };

      OmniSelect.prototype._getURIParameter = function(name) {
        var i, sPageURL, sParameterName, sURLVariables, _i, _ref;
        sPageURL = window.location.search.substring(1);
        sURLVariables = sPageURL.split('&');
        for (i = _i = 0, _ref = sURLVariables.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          sParameterName = sURLVariables[i].split('=');
          if (sParameterName[0] === name) {
            return decodeURIComponent(sParameterName[1]);
          }
        }
      };

      return OmniSelect;

    })();
    return window.OmniSelect = OmniSelect;
  })(jQuery, window);

}).call(this);
